# Generated by Django 2.0.9 on 2018-12-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dumb',
        ),
    ]
