# Generated by Django 2.0.9 on 2018-12-28 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(default=None, null=True)),
                ('last_attempt', models.DateTimeField(default=None, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailinglist.Message')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailinglist.Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberMessageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
